### ISSUE TITLE
Editable installs raise errors on hot reload

### ISSUE THREAD

**Issue by andyvandy** [cunnane/xloil#114]
## Issue

 

When editing an [editably installed](https://setuptools.pypa.io/en/latest/userguide/development_mode.html) module, hot reloading throws an error.

 

```

[14:26:55] [error] During Event < local git repo path>: KeyError: KeyError: '< local git repo path>'

Traceback (most recent call last):

  File "<site packages path>\xloil\importer.py", line 101, in _on_file_modified

    addin_path = self.module_addin[filepath]

                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^

KeyError: '< local git repo path>'

```

 

## Trigger

 

This issue is new in version `0.18.8` and is triggered by this line

https://github.com/cunnane/xloil/blob/94314c27c9fa0830a2769878dada709f6c47cdda/libs/xlOil_Python/Package/xloil/importer.py#L99

 

## Potential Solution

 

We could update the `self.module_addin` lookup above in `_on_file_modified` to first search for the module name and then the filepath if not found.

 

## Details/Root Cause

 

This module is loaded via the ini file `LoadModules` plugin setting from a custom named xll.

 

I believe a file watch is registered here since the predicate is false ( `module.__spec__.origin='C:\\localgitrepo\\package\\submodule\\file.py'` not in `site.PREFIXES`)

https://github.com/cunnane/xloil/blob/94314c27c9fa0830a2769878dada709f6c47cdda/libs/xlOil_Python/Package/xloil/importer.py#L84-L87

 

`self.module_addin` has two applicable entries, one for the module name -> custom xll, the other for the package root `__init__.py` file -> xloil.dll.

 

I believe these are set by these lines

 

https://github.com/cunnane/xloil/blob/94314c27c9fa0830a2769878dada709f6c47cdda/libs/xlOil_Python/Package/xloil/importer.py#L203

https://github.com/cunnane/xloil/blob/94314c27c9fa0830a2769878dada709f6c47cdda/libs/xlOil_Python/Package/xloil/importer.py#L365

**Comment by cunnane** [comment]
Thank you for the detailed debug!  This should be fixed in 0.19.1, which I just released.

**Comment by gnyuan** [comment]
When setting `debugger = "vscode"` instead of `debugger = ""`, I still encounter the following error:
```[2024-09-18 09:37:38.888] [logger] [error] [Main.cpp:418] xloil_python_init failed: KeyError: KeyError: ''
Traceback (most recent call last):
  File "D:\workspace\excel\.venv\Lib\site-packages\xloil\debug.py", line 166, in use_debugger
    debugpy_listen(**kwargs)
  File "D:\workspace\excel\.venv\Lib\site-packages\xloil\debug.py", line 56, in debugpy_listen
    addin = xloil.source_addin()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\excel\.venv\Lib\site-packages\xloil\importer.py", line 141, in source_addin
    else xloil_core.xloil_addins[addin_path]
        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: ''
```
