### ISSUE TITLE
Publishing numpy string array from RTDPublisher corrupts heap

### ISSUE THREAD

**Issue by andyvandy** [cunnane/xloil#127]
Hi Steven, hope the new year is treating you well!

I've tracked down a bug which is resulting in excel crashing suddenly with no warning. I believe it's tied to publishing numpy string arrays and when memory is freed on the python side. 

### Repro

Here's an example that can be run with a sheet locally. I've reproduced the crash on win10/win11, 32/64 bit, xloil 0.18.5/0.19.1 . I can provide more example cases if that would be helpful.  

One additional case I need to send myself from another PC was if a global variable rather than local is published then the sheet doesn't crash. ( presumably since memory isn't freed )

```python

import time
import xloil as xlo
import asyncio

TOPIC = "BUGHUNT"
_rtdServer = xlo.RtdServer()

async def crashes_1():
    _rtdServer.publish(TOPIC, [["danger"]])  
    await asyncio.sleep(10)
    _rtdServer.publish(TOPIC, [["safe!",1]])  

async def safe_1():
    _rtdServer.publish(TOPIC, [["no danger", 1]])  
    await asyncio.sleep(10)
    _rtdServer.publish(TOPIC, [["safe!",1]])  

async def safe_2():
    _rtdServer.publish(TOPIC, [["danger"]])  
    _rtdServer.publish(TOPIC, [["no danger", 1]])  
    await asyncio.sleep(10)
    _rtdServer.publish(TOPIC, [["safe!",1]])  

async def crashes_2():
    _rtdServer.publish(TOPIC, ["danger"])  

async def safe_3():
    _rtdServer.publish(TOPIC, "safe")  

async def crashes_3():
    _rtdServer.publish(TOPIC, ["danger"])  
    time.sleep(10)

async def safe_4():
    _rtdServer.publish(TOPIC, [["safe"],[1]])  

async def crashes_4():
    """Tuples aren't safe either..."""
    _rtdServer.publish(TOPIC, ("danger",))  

async def safe_6():
    """unless they aren't 1x1"""
    _rtdServer.publish(TOPIC, ("safe","safe"))  

TARGET_FUNC = crashes_4

class ExamplePublisher(xlo.RtdPublisher):
    def __init__(self):
        super().__init__()  # You *must* call this explicitly or the python binding library will crash
        self._task = None

    def connect(self, num_subscribers):
        if self.done():
            self._task = xlo.get_async_loop().create_task(TARGET_FUNC())

    def disconnect(self, num_subscribers):
        if num_subscribers == 0:
            self.real_stop()
            return True # This publisher is no longer required: schedule it for destruction

    def stop(self):
        pass

    def real_stop(self):
        if self._task is not None:
            self._task.cancel()

    def done(self):
        return self._task is None or self._task.done()

    def topic(self):
        return TOPIC

@xlo.func(local=False,rtd = True)  

def xloilRTDFunc( ):
    if _rtdServer.peek(TOPIC) is None:
        publisher = ExamplePublisher()
        _rtdServer.start(publisher)

    return _rtdServer.subscribe(TOPIC)

@xlo.func(local=False,rtd = True)  
async def xloilDirectRTDFunc( ):
    """Note that directly returning the values doesn't cause the same crashes"""
    yield "safe1"
    await asyncio.sleep(2)
    yield ["safe2"]
    await asyncio.sleep(2)
    yield [["safe3"]]
    await asyncio.sleep(2)
    yield ["safe4",1]
 
```

I managed to compile xloil locally and drop breakpoints. Unfortunately it has been hard to spot exactly where the issue is here since the crash doesn't occur right away. Please let me know if there's anything I can test or check which would be helpful in narrowing this down!

**Comment by cunnane** [comment]
I think this should be fixed by [this commit](https://github.com/cunnane/xloil/commit/e8e08d0cc6099775bab749c4fe8b7722b9e9a412) which is in v0.20 (just released).  Your example code will drop into the tuple converter rather than the numpy converter.

**Comment by andyvandy** [comment]
I tested this yesterday and ran into more crashing than before. I just pulled and locally compiled the latest code today and found that the  release build is crashing for me but the debug build isn't. ( 64bit py311)

`crashes_3` and `crashes_4` from the example are running in debug now but the nested array `crashes_1` is returning #NA

I'll try to dig deeper to gather more details and hopefully figure out why. 🕵️

**Comment by andyvandy** [comment]
still not sure of the exact root but one more hint.

Updating the above example to include a type converter which casts to string seems to prevent the crash which narrows the search somewhat.

```python

@xlo.converter(xlo.ExcelArray, direction = "read", range =True)
def casttostring(x):
    return str(x)

@xlo.func(local=False,rtd = True)  
def xloilRTDFunc( ):
    if _rtdServer.peek(TOPIC) is None:
        publisher = ExamplePublisher()
        _rtdServer.start(publisher)
    return _rtdServer.subscribe(TOPIC,casttostring._xloil_arg_reader[0])

```

I also tried expanding the lock `_mutexNewValues` since I noticed that the compiler optimizes away to the swap variable in release in my local build. It didn't seem to be the magic fix I'd hoped for though.

**Comment by cunnane** [comment]
Unfortunately I can't replicate any of these issues (with v0.20 and your fix to *innerIter* and py3.11 x64).  Just wanted to check that when you run the release build, it's definitely not picking up an older xloil binary?  (You can the the `xloil clean` command to do a full remove, assuming you have the xloil wheel installed).

**Comment by andyvandy** [comment]
I've gotten a step closer!

I realized that ingesting a range of all strings results in a numpy array with unicode dtype. I can now reliably reproduce the crashes by just creating and returning a 2d numpy array with that dtype and only 1 column.

```python
import xloil as xlo
import numpy as np
@xlo.func(local=False)
def nparray():
    arr = np.array(['danger'], dtype='U') # okay
    arr = np.array([['danger', 'NOW()']], dtype='object') #okay
    arr = np.array([['danger',"danger!"],['danger',"danger!"]], dtype='<U7') # no crash!
    arr = [['danger']] # okay
    arr = np.array([['danger']], dtype='U') #crashes
    return arr

```


I played around with this locally for some time and tried to use the succeeding npy_object branch to compare against. When I replace these lines it stops the crashing, when I recompile with the original source, it crashes once more.  I cleaned my solution as well as uninstalled the global xloil. 

https://github.com/cunnane/xloil/blob/d0506f0494dab63a815f066b0c948b9adf431881/libs/xlOil_Python/TypeConversion/NumpyToExcel.cpp#L95-L105

```python
SequentialArrayBuilder builder((uint32_t)dims[0], (uint32_t)dims[1],
  converter.stringLength);
auto charAllocator = builder.charAllocator();
for (auto i = 0; i < dims[0]; ++i)
  for (auto j = 0; j < dims[1]; ++j)
  {
    auto p = PyArray_GETPTR2(pyArr, i, j);
    builder.emplace(FromPyObj<detail::ReturnToCache, true>()(PyUnicode_FromKindAndData(PyUnicode_4BYTE_KIND,p,6), charAllocator));
  }
```
( obviously the hardcoded length of 6 would need to be replaced ) I'm not sure if this would leak resources either.

This feels like it may be tied to Excel string memory management.

If you still don't see these crashes, I wonder if it's tied to Excel version? Here's one of versions ( reproduced on a few computers ) 
`Microsoft® Excel® for Microsoft 365 MSO (Version 2501 Build 16.0.18429.20114) 64-bit `

**Comment by andyvandy** [comment]
Numpy 2.2.2 (latest)

**Comment by andyvandy** [comment]
Interesting, I just tested with numpy 1.26.4 and observe the same behaviour for both dtype inference from excel as well as crashing when returning the 1x1 unicode dtype array.

Is the latest example reproducible on your end or is there still some environment difference at play here?

**Comment by andyvandy** [comment]
Alright, managed to narrow it down again. Using numpy 1.26.4, I see the crashing begins in 0.17.12 and that if we go back all the way to v0.17.11 the immediate crashes stop.
 https://github.com/cunnane/xloil/compare/v0.17.11...v0.17.12

**Comment by cunnane** [comment]
I can't replicate any crashes, but if in NumpyHelpers.h you reverse the
order of *itemLength *and *stringLength* at lines 199/200, does that stop
the crashes?

**Comment by andyvandy** [comment]
That fixes it! Nice spot!


Tracing through (Mostly to make sure I understand) I see that `stringLength` gets initialized as `0` here since it's initialized first ([point #3 in the 'Initialization Order' section
 ](https://en.cppreference.com/w/cpp/language/constructor) )

https://github.com/cunnane/xloil/blob/d0506f0494dab63a815f066b0c948b9adf431881/libs/xlOil_Python/TypeConversion/NumpyHelpers.h#L199-L211

That results in 0 length getting passed to the ExcelArrayBuilder Here and us writing past the end of the buffer

https://github.com/cunnane/xloil/blob/d0506f0494dab63a815f066b0c948b9adf431881/libs/xlOil_Python/TypeConversion/NumpyToExcel.cpp#L95-L96

I was curious about why the 1d array case didn't throw and saw that the value was a larger non-zero value such as 114528 or 102688 which may result in inefficient overallocation but not a crash. 

 As for why it doesn't crash in DEBUG, I see the memory is pre initialized so I again get a large value. Value I get is `104856` which divided by 2 for `charMultiple` means that itemlength was `52428`.  `52428` is the `uint16_t` representation of the default hex `cccc` initialized by visual studio.

**Comment by cunnane** [comment]
The problem was that *itemLength* is not initialised before being used to calculate *stringLength*, so it just takes a "random" value, which is why it doesn't crash consistently between you and me and across numpy versions.  In debug builds things are initialised to a "bad" value to try to catch these kind of bugs, but as you note this value just results in an overly large array.

**Comment by andyvandy** [comment]
> The problem was that _itemLength_ is not initialised before being used to calculate _stringLength_, so it just takes a "random" value, which is why it doesn't crash consistently between you and me and across numpy versions. In debug builds things are initialised to a "bad" value to try to catch these kind of bugs, but as you note this value just results in an overly large array.

Exactly! This explains why I had such a hard time narrowing down to a consistently reproducible example. (At least on my end)

Thanks for all the help here! Looking forward to the next release!

**Comment by cunnane** [comment]
I think everything is fixed here with 0.20.1, let me know if not.
