### ISSUE TITLE
Excel crashes at startup (loading xll by drop) due to LoadBeforeCore=true option setting in XLL-specific ini file.

### ISSUE THREAD

**Issue by mskz1** [cunnane/xloil#26]
Hi Steven,
Thank you for your great work!

I have created a UDF add-in (xs_udf_xloil.xll) and it normally works without any problems.
But for add-in distribution , I'm editing a XLL-specific ini file (xs_udf_xloil.ini) with LoadBeforeCore=true, Excel crashes on startup.
(loading xll by drop)

Here is the log file.
```
[2023-01-12 17:02:50.330] [logger] [info] [AddinLoader.cpp:57] Found core settings file 'C:\Users\UUUUU\OneDrive - XXXXX\YYYY\EXCEL\xloil_sample\xlset_udf_winpython\xs_udf_xloil.ini' for 'C:\Users\UUUUU\OneDrive - XXXXX\YYYY\EXCEL\xloil_sample\xlset_udf_winpython\xs_udf_xloil.xll'
[2023-01-12 17:02:50.331] [logger] [info] [AddinLoader.cpp:57] Found core settings file 'C:\Users\UUUUU\AppData\Roaming\xlOil\xlOil.ini' for 'D:\WPy64-38100\python-3.8.10.amd64\share\xloil\xlOil.dll'
[2023-01-12 17:02:50.331] [logger] [debug] [FuncRegistry.cpp:190] Registering "xloRunInXLLContext" at entry point xloRunInXLLContext with 0 args
[2023-01-12 17:02:50.331] [logger] [debug] [FuncRegistry.cpp:190] Registering "xloVersion" at entry point xloVersion with 0 args
[2023-01-12 17:02:50.331] [logger] [debug] [FuncRegistry.cpp:190] Registering "xloLog" at entry point xloLog with 1 args
[2023-01-12 17:02:50.331] [logger] [debug] [FuncRegistry.cpp:190] Registering "xloHelp" at entry point xloHelp with 1 args
[2023-01-12 17:02:50.331] [logger] [debug] [FuncRegistry.cpp:190] Registering "xloRef" at entry point xloRef with 1 args
[2023-01-12 17:02:50.331] [logger] [debug] [FuncRegistry.cpp:190] Registering "xloVal" at entry point xloVal with 1 args
[2023-01-12 17:02:50.331] [logger] [debug] [FuncRegistry.cpp:190] Registering "RegistrationInfo_d5a424b6966b5f75bd3e6b99ea363a57" at entry point IntellisenseRegistrationInfo with 1 args
[2023-01-12 17:02:50.339] [logger] [debug] [Connect.cpp:81] Made COM connection to Excel at 'C:\Program Files\Microsoft Office\Root\Office16' with hwnd=1905292
[2023-01-12 17:03:21.567] [logger] [debug] [Throw.cpp:17] COM Error -0x7ff5f821 (in XllContextInvoke.cpp:80 during xloil::runInXllContext::<lambda_2fe688e41d0eef07f9c0210faea801eb>::operator ())
[2023-01-12 17:03:21.567] [logger] [error] [ExcelThread.cpp:107] Internal error running main thread queue: COM Error -0x7ff5f821
```
Is there something wrong with my procedure?

windows10
python3.8.10(WinPython)
xlOil 0.16.1

**Comment by cunnane** [comment]
Thanks for reporting this.  This is fixed in xlOil v0.16.2 which is available on PyPI.

**Comment by mskz1** [comment]
I updated to 0.16.2 and Excel crash problem is fixed.
Thanks a lot!

But have a problem about XLL-specific ini file setting.
The module `xs_udf_xloil.py` loaded by `xs_udf_xloil.xll` is in `D:\src_sample`.
I set `XLOIL_PYTHON_PATH='''D:\src_sample'''` in `xs_udf_xloil.ini` but setting of `%APPDATA%\xlOil\xlOil.ini` or `PythonXY\share\xloil\xlOil.ini` (`XLOIL_PYTHON_PATH=";"`) has priority, so XLL-specific setting does not take effect in the module search path, resulting a ModuleNotFoundError.
[2023-0113.log](https://github.com/cunnane/xloil/files/10409312/2023-0113.log)

**Comment by cunnane** [comment]
I've spotted a race condition in the addin loading which could be causing this.  Can you try v0.16.3?  If it's not that, can you please post the ini file you are using?

**Comment by mskz1** [comment]
I update to v0.16.3, but still have the same problem.

Attach the log and ini file.
[0116.log](https://github.com/cunnane/xloil/files/10421576/0116.log)
[xs_udf_xloil.zip](https://github.com/cunnane/xloil/files/10421583/xs_udf_xloil.zip)

If  `XLOIL_PYTHON_PATH='''D:\src_sample'''` is set in `%APPDATA%\xlOil\xlOil.ini`, it works without problems.

**Comment by cunnane** [comment]
It appears to be loading in the ini files in the right order, could you try changing the last line of your ``xs_udf_xloil.ini`` to be ``PYTHONPATH='''%PYTHONPATH%;D:\src_sample'''`` ?

**Comment by cunnane** [comment]
Sorry, I missed something very silly!  I've patched this in v0.16.4

**Comment by mskz1** [comment]
I update to v0.16.4 and the problem is fixed.
Thank you so match!

**Comment by cunnane** [comment]
Glad it's working for you!

**Comment by karl-emilbp** [comment]
Update:
This problem is still occurring in xloil v0.17.5, but when downgrading to 0.16.4, the problem is fixed.

**Comment by cunnane** [comment]
Thanks, it turned out to be a different set of problems with the same symptoms!  I've just released v0.17.7 where this should be fixed.
