### ISSUE TITLE
COM error at Matplotlib figure return function.

### ISSUE THREAD

**Issue by mskz1** [cunnane/xloil#33]
I'm trying to function that return matploilib figure.
My own and sample function both cause com error.
Is there anything wrong with my procedure?

```
import xloil as xlo
import xloil.matplotlib
from matplotlib import pyplot
from fem_2d import *

# my own function
@xlo.func(macro=True)
def plot_model():
    fig, ax = plt.subplots()
    mdl = make_portal_frame2_for_model_plot()
    mdl.analyze()
    mdl.plot_model(ax)
    return fig

# sample function
@xlo.func(macro=True)
def pyTestPlot(x, y, **kwargs):
    fig = pyplot.figure()
    ax = fig.add_subplot(111)
    ax.plot(x, y, **kwargs)
    return fig
```
Please refer the log file.
In log, Japanese message "種類が一致しません。" means "Type mismatch."
[log_2023-0209-2.txt](https://github.com/cunnane/xloil/files/10696150/log_2023-0209-2.txt)

windows10
python3.8.10(WinPython)
xlOil 0.16.4
(due to the [issue#32](https://github.com/cunnane/xloil/issues/32#issue-1577376629) of 0.17.1)

**Comment by cunnane** [comment]
I suspect this is due to localisation and I think I know what's happening, will investigate...

**Comment by cunnane** [comment]
This should be fixed in v0.17.3 now on PyPI

**Comment by mskz1** [comment]
Thank you for investigating and modifying the code.
I updated to 0.17.3, but still have same error.

I attach the log file for your information.
[log-0213.txt](https://github.com/cunnane/xloil/files/10719701/log-0213.txt)


To simplify the problem, I tried sample function (pyTestPlot) in some condition.

```
import xloil as xlo
import xloil.matplotlib
from matplotlib import pyplot

@xlo.func(macro=True)
def pyTestPlot(x, y, **kwargs):
    fig = pyplot.figure()
    ax = fig.add_subplot(111)
    ax.plot(x, y, **kwargs)
    return fig
```

In my environment, as a workbook module function, the function return matplotlib fig successfuly.
But as a load module function, pyTestPlot function get error.

As a workbook module function.
The pyTestPlot function is in sample.py at the same folder of sample.xlsm.
![scrn-0213](https://user-images.githubusercontent.com/16732180/218397866-c22d8d6e-3711-4818-b694-0bc2546bcfb9.png)
[log-0213.txt](https://github.com/cunnane/xloil/files/10719718/log-0213.txt)

As a load module function.
The pyTestPlot function is in sample.py at D:\src_sample\plot_sample folder and the xll-specific ini file is configured to load it.
![scrn-0213](https://user-images.githubusercontent.com/16732180/218398021-053d3ee3-ac8c-4b26-bc30-d1cb813b7e62.png)
[log-0213.txt](https://github.com/cunnane/xloil/files/10719725/log-0213.txt)

Is there any solution?

**Comment by cunnane** [comment]
Thanks for the great debugging help with isolating this problem!  It should be fixed in v0.17.4 which I've just released.

**Comment by mskz1** [comment]
Thank you for fixing the problem!
I updated to v0.17.4 and get matplotlib figure successfully
I really appreciate your contribution.

I would like to still continue to develop my add-in with xlOil.
Thank you so much!

**Comment by cunnane** [comment]
Glad it worked for you!  Let me know if anything else comes up.
